/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_sevenzipjbinding_impl_OutArchiveImpl */

#ifndef _Included_net_sf_sevenzipjbinding_impl_OutArchiveImpl
#define _Included_net_sf_sevenzipjbinding_impl_OutArchiveImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sf_sevenzipjbinding_impl_OutArchiveImpl
 * Method:    nativeSetHeaderEncryption
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_sf_sevenzipjbinding_impl_OutArchiveImpl_nativeSetHeaderEncryption
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     net_sf_sevenzipjbinding_impl_OutArchiveImpl
 * Method:    nativeSetLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_sf_sevenzipjbinding_impl_OutArchiveImpl_nativeSetLevel
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_sf_sevenzipjbinding_impl_OutArchiveImpl
 * Method:    nativeSetSolidSpec
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_sf_sevenzipjbinding_impl_OutArchiveImpl_nativeSetSolidSpec
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_sf_sevenzipjbinding_impl_OutArchiveImpl
 * Method:    nativeSetMultithreading
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_sf_sevenzipjbinding_impl_OutArchiveImpl_nativeSetMultithreading
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_sf_sevenzipjbinding_impl_OutArchiveImpl
 * Method:    nativeUpdateItems
 * Signature: (Lnet/sf/sevenzipjbinding/ISequentialOutStream;ILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_net_sf_sevenzipjbinding_impl_OutArchiveImpl_nativeUpdateItems
  (JNIEnv *, jobject, jobject, jint, jobject);

/*
 * Class:     net_sf_sevenzipjbinding_impl_OutArchiveImpl
 * Method:    nativeClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_sevenzipjbinding_impl_OutArchiveImpl_nativeClose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
