/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_sevenzipjbinding_impl_InArchiveImpl_ExtractSlowCryptoCallback */

#ifndef _Included_net_sf_sevenzipjbinding_impl_InArchiveImpl_ExtractSlowCryptoCallback
#define _Included_net_sf_sevenzipjbinding_impl_InArchiveImpl_ExtractSlowCryptoCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
