/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_sevenzipjbinding_SevenZip_DummyOpenArchiveCallback */

#ifndef _Included_net_sf_sevenzipjbinding_SevenZip_DummyOpenArchiveCallback
#define _Included_net_sf_sevenzipjbinding_SevenZip_DummyOpenArchiveCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
