/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_sevenzipjbinding_SevenZip */

#ifndef _Included_net_sf_sevenzipjbinding_SevenZip
#define _Included_net_sf_sevenzipjbinding_SevenZip
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sf_sevenzipjbinding_SevenZip
 * Method:    nativeOpenArchive
 * Signature: (Lnet/sf/sevenzipjbinding/ArchiveFormat;Lnet/sf/sevenzipjbinding/IInStream;Lnet/sf/sevenzipjbinding/IArchiveOpenCallback;)Lnet/sf/sevenzipjbinding/IInArchive;
 */
JNIEXPORT jobject JNICALL Java_net_sf_sevenzipjbinding_SevenZip_nativeOpenArchive
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     net_sf_sevenzipjbinding_SevenZip
 * Method:    nativeCreateArchive
 * Signature: (Lnet/sf/sevenzipjbinding/impl/OutArchiveImpl;Lnet/sf/sevenzipjbinding/ArchiveFormat;)V
 */
JNIEXPORT void JNICALL Java_net_sf_sevenzipjbinding_SevenZip_nativeCreateArchive
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     net_sf_sevenzipjbinding_SevenZip
 * Method:    nativeInitSevenZipLibrary
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sf_sevenzipjbinding_SevenZip_nativeInitSevenZipLibrary
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_sevenzipjbinding_SevenZip
 * Method:    nativeGetVersionMajor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sf_sevenzipjbinding_SevenZip_nativeGetVersionMajor
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_sevenzipjbinding_SevenZip
 * Method:    nativeGetVersionMinor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sf_sevenzipjbinding_SevenZip_nativeGetVersionMinor
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_sevenzipjbinding_SevenZip
 * Method:    nativeGetVersionBuild
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sf_sevenzipjbinding_SevenZip_nativeGetVersionBuild
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_sevenzipjbinding_SevenZip
 * Method:    nativeGetVersionVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sf_sevenzipjbinding_SevenZip_nativeGetVersionVersion
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_sevenzipjbinding_SevenZip
 * Method:    nativeGetVersionDate
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sf_sevenzipjbinding_SevenZip_nativeGetVersionDate
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_sevenzipjbinding_SevenZip
 * Method:    nativeGetVersionCopyright
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sf_sevenzipjbinding_SevenZip_nativeGetVersionCopyright
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
